// Color variable names for use in JS/TS (hybrid approach)
export const COLORS = {
  primary: 'var(--primary-color)',
  primaryDark: 'var(--primary-color-dark)',
  secondary: 'var(--secondary-color)',
  backgroundMain: 'var(--background-main)',
  backgroundLight: 'var(--background-light)',
  backgroundGrey: 'var(--background-grey)',
  backgroundCard: 'var(--background-card)',
  backgroundWarning: 'var(--background-warning)',
  backgroundError: 'var(--background-error)',
  backgroundInfo: 'var(--background-info)',
  backgroundSuccess: 'var(--background-success)',
  backgroundNote: 'var(--background-note)',
  borderMain: 'var(--border-main)',
  borderLight: 'var(--border-light)',
  borderGrey: 'var(--border-grey)',
  borderInput: 'var(--border-input)',
  textMain: 'var(--text-main)',
  textSecondary: 'var(--text-secondary)',
  textLight: 'var(--text-light)',
  textGrey: 'var(--text-grey)',
  textPlaceholder: 'var(--text-placeholder)',
  textWarning: 'var(--text-warning)',
  textError: 'var(--text-error)',
  textInfo: 'var(--text-info)',
  textSuccess: 'var(--text-success)',
  iconInfo: 'var(--icon-info)',
};
